name: Main branch execution

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Main branch execution
    environment: prod
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npx nx start-ci-run --distribute-on=".nx/workflows/distribution-config.yaml" --stop-agents-after=lint,test,build
      - run: npm ci --legacy-peer-deps

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      - name: Enforce all conformance rules
        run: npx nx-cloud conformance:check
        
      - name: Hydrate Nx Cache
        run: npx nx run-many -t lint test build
