name: Main branch execution

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Main branch execution
    environment: prod
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js"
      - run: npm ci --legacy-peer-deps
      - run: npx nx run-many -t lint test build e2e-ci
